### ISSUE TITLE
yahoo-finance-cookie file now only has comment lines

### ISSUE THREAD

**Issue by sjlGH** [foxadb/yahoo-finance#11]
The package used to work perfect.  But recently, the cookie file generated is sort of empty.  In the yahoo-finance-cookie file, I only see the comment lines:

# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

Anyone is having the same issue?

By the way, the function that I stepped into is:
getYahooCrumbCookie(std::string url,
                         std::string *crumb,
                         std::string *cookie)
the url that I used is: https://finance.yahoo.com/quote/IBM/?p=IBM

**Comment by foxadb** [comment]
Hello @sjlGH 

This issue might be related to the fact that Yahoo Finance API doesn't require the crumbstore cookie mechanism anymore to fetch stock data.

The `getYahooCrumbCookie` function you have mentioned has been removed since I have merged https://github.com/foxadb/yahoo-finance/pull/10

Hope it'll fix your issue :pray:

**Comment by sjlGH** [comment]
Great! Thanks @foxadb .  Yes, it does.
